### ISSUE TITLE
Add around_action-based implementation

### ISSUE THREAD

**Issue by athal7** [godaddy/activerecord-delay_touching#1]
This is really great work and very easy to implement! One thing that could make it even easier is to add a method into ActionController::Base that could be implemented in an around_action to wrap the entire controller action. The method would look something like this:

```ruby
def delay_touching
  ActiveRecord::Base.delay_touching { yield }
end
```

**Comment by mtuckergd** [comment]
this is a nice idea but seems fairly trivial to implement in an app that wants it, using the above code and defining the around filter. I don't feel the necessity to add to the gem, but if you do please do submit a PR. 

Thanks!

**Comment by SirRawlins** [comment]
Stumbled across this old issue while looking at this myself. I've rolled this into an ActionController module which can be included in any controller nice and easily.

```ruby
#
# Action controller extension which wraps all actions
# within the ActiveRecord::Base.delay_touching callback so that
# it stops overflow of touch callbacks.
#
# https://github.com/godaddy/activerecord-delay_touching
#
# Usage: include ActionController::DelayTouching
#
module ActionController
	module DelayTouching
		# Implement this as a concern.
		extend ActiveSupport::Concern

		included do
			# Wrap all controller actions with the delay
			# touching block.
			#
			# We prepend to ensure wrapping happens as early as possible
			# in the call stack to maximise the benefit.
			prepend_around_action :delay_touching
		end

		private

			# Delay touching to once per
			# transaction to prevent the noise.
			def delay_touching
				# Use the gem to wrap every action within the app.
				ActiveRecord::Base.delay_touching { yield }
			end
	end
end
```

Just in case anyone else ends up here and finds it useful.
