### ISSUE TITLE
can't write unknown attribute :time in Rails 5

### ISSUE THREAD

**Issue by dfyx** [godaddy/activerecord-delay_touching#13]
I have the following in my `ApplicationController`

``` ruby
around_action :delay_touching

def delay_touching
  ActiveRecord::Base.delay_touching { yield }
end
```

In Rails 4.2, everything works but after the update to Rails 5 I get the following error in lots of rspec tests:

```
Failure/Error: ActiveRecord::Base.delay_touching { yield }

ActiveModel::MissingAttributeError:
  can't write unknown attribute `{:time=>2016-07-19 13:46:06 UTC}
```

When I remove the `around_action`, all specs run as expected.

**Comment by dfyx** [comment]
Here's the relevant stack trace:

```
# /home/dfyx/.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0/lib/active_record/attribute.rb:182:in `with_value_from_database'
# /home/dfyx/.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0/lib/active_record/attribute_set.rb:51:in `write_from_user'
# /home/dfyx/.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0/lib/active_record/attribute_methods/write.rb:50:in `write_attribute_with_type_cast'
# /home/dfyx/.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0/lib/active_record/attribute_methods/write.rb:32:in `write_attribute'
# /home/dfyx/.rvm/gems/ruby-2.3.0/gems/activerecord-delay_touching-1.0.1/lib/activerecord/delay_touching.rb:91:in `block (3 levels) in touch_records'
# /home/dfyx/.rvm/gems/ruby-2.3.0/gems/activerecord-delay_touching-1.0.1/lib/activerecord/delay_touching.rb:90:in `instance_eval'
# /home/dfyx/.rvm/gems/ruby-2.3.0/gems/activerecord-delay_touching-1.0.1/lib/activerecord/delay_touching.rb:90:in `block (2 levels) in touch_records'
# /home/dfyx/.rvm/gems/ruby-2.3.0/gems/activerecord-delay_touching-1.0.1/lib/activerecord/delay_touching.rb:88:in `each'
# /home/dfyx/.rvm/gems/ruby-2.3.0/gems/activerecord-delay_touching-1.0.1/lib/activerecord/delay_touching.rb:88:in `block in touch_records'
# /home/dfyx/.rvm/gems/ruby-2.3.0/gems/activerecord-delay_touching-1.0.1/lib/activerecord/delay_touching.rb:85:in `each'
# /home/dfyx/.rvm/gems/ruby-2.3.0/gems/activerecord-delay_touching-1.0.1/lib/activerecord/delay_touching.rb:85:in `touch_records'
# /home/dfyx/.rvm/gems/ruby-2.3.0/gems/activerecord-delay_touching-1.0.1/lib/activerecord/delay_touching.rb:67:in `block (3 levels) in apply'
# /home/dfyx/.rvm/gems/ruby-2.3.0/gems/activerecord-delay_touching-1.0.1/lib/activerecord/delay_touching.rb:66:in `each'
# /home/dfyx/.rvm/gems/ruby-2.3.0/gems/activerecord-delay_touching-1.0.1/lib/activerecord/delay_touching.rb:66:in `block (2 levels) in apply'
# /home/dfyx/.rvm/gems/ruby-2.3.0/gems/activerecord-delay_touching-1.0.1/lib/activerecord/delay_touching.rb:65:in `each'
# /home/dfyx/.rvm/gems/ruby-2.3.0/gems/activerecord-delay_touching-1.0.1/lib/activerecord/delay_touching.rb:65:in `block in apply'
# /home/dfyx/.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
# /home/dfyx/.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
# /home/dfyx/.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
# /home/dfyx/.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0/lib/active_record/transactions.rb:211:in `transaction'
# /home/dfyx/.rvm/gems/ruby-2.3.0/gems/activerecord-delay_touching-1.0.1/lib/activerecord/delay_touching.rb:64:in `apply'
# /home/dfyx/.rvm/gems/ruby-2.3.0/gems/activerecord-delay_touching-1.0.1/lib/activerecord/delay_touching.rb:54:in `call'
# /home/dfyx/.rvm/gems/ruby-2.3.0/gems/activerecord-delay_touching-1.0.1/lib/activerecord/delay_touching.rb:31:in `delay_touching'
     pp/controllers/application_controller.rb:46:in `delay_touching'
```

**Comment by kylekermgard** [comment]
I had the same issue. It looks like the gem needs to be updated for rails 5. As a work around I monkey patched the gem in an initializer file.

module ActiveRecord
  module DelayTouching
    class State
      def add_record(record, *columns)
        columns << nil if columns.empty? #if no arguments are passed, we will use nil to infer default column
        columns.each do |column|
          @records[column] += [record] unless @already_updated_records[column].include?(record) || column.is_a?(Hash)
        end
      end
    end

    def self.touch_records(attr, klass, records)
      attributes = records.first.send(:timestamp_attributes_for_update_in_model)
      attributes << attr if attr

      if attributes.present?
        current_time = records.first.send(:current_time_from_proper_timezone)
        changes = {}

        attributes.each do |column|
          column = column.to_s
          changes[column] = current_time
          records.each do |record|
            next if record.destroyed?
            record.instance_eval do
              write_attribute column, current_time
              @changed_attributes && @changed_attributes.except!(*changes.keys)
            end
          end
        end

        klass.unscoped.where(klass.primary_key => records).update_all(changes)
      end
      state.updated attr, records
      records.each { |record| record.run_callbacks(:touch) }
    end
  end
end

**Comment by mtuckergd** [comment]
Thanks @kylekermgard. I haven't had a chance to look at this recently. If your monkey patch works, would you be interested in submitting submitting a PR with it applied in the source? Otherwise, I'll try to get to this as soon as possible, though I can't make any promise on when that will happen right now.

**Comment by mtuckergd** [comment]
At this point, I'm not planning to upgrade this library to support Rails 5, due to similar functionality that is now provided in the Rails core (see https://github.com/rails/rails/pull/19324).
Please submit a new issue if you have a compelling reason to pursue adding Rails 5 support.
Thanks!

**Comment by Kenneth-KT** [comment]
@kritik A pull request has been created to support Rails 5 with Rails 4 backward compatibility: https://github.com/godaddy/activerecord-delay_touching/pull/21
I have also published a new gem call `activerecord5-delay_touching` to [rubygems.org](https://rubygems.org/gems/activerecord5-delay_touching), feel free to it until the maintainer publish my change.

**Comment by Kenneth-KT** [comment]
@dfyx @kylekermgard 
A pull request has been created to support Rails 5 with Rails 4 backward compatibility: https://github.com/godaddy/activerecord-delay_touching/pull/21
I have also published a new gem call `activerecord5_delay_touching` to [rubygems.org](https://rubygems.org/gems/activerecord5_delay_touching), feel free to use it until the maintainer publish my change.

**Edit**: Due to some issue, I have yanked the `activerecord5-delay_touching` gem that I published and published another gem called `activerecord5_delay_touching`.
