### ISSUE TITLE
Is there a possibility to support Rails 3.2 ?

### ISSUE THREAD

**Issue by salimane** [godaddy/activerecord-delay_touching#6]
It would be super awesome if we could support rails 3.2 for some legacy project out there :)
Thanks

**Comment by mtuckergd** [comment]
Hey @salimane. Are you seeing problems in Rails 3.2? If so, can you post the errors you're seeing? I think we used to use this on Rails 3.2 without issue, but not positive on that and would be happy to take a look.

**Comment by salimane** [comment]
@mtuckergd , there is a hard dependency here https://github.com/godaddy/activerecord-delay_touching/blob/master/activerecord-delay_touching.gemspec#L21 . So when I tried to run ``bundle`` with rails 3.2.21 I got : 
```shell
Bundler could not find compatible versions for gem "activerecord":
  In snapshot (Gemfile.lock):
    activerecord (= 3.2.21)

  In Gemfile:
    activerecord-delay_touching (~> 1.0.0) ruby depends on
      activerecord (>= 4.2) ruby
```

**Comment by mtuckergd** [comment]
@salimane I see. You should be using the older branch version of this library: https://github.com/godaddy/activerecord-delay_touching/tree/pre-activerecord-4.2.

ActiveRecord introduced a breaking change in the touch signature at AR 4.2, so we branched the support of these versions. Master is now AR 4.2+ and the branch supports versions prior. 

You should be able to pin to that branch if you reference GitHub directly, or version pin to "~> 0.0.1" to get the latest from RubyGems for AR < 4.2.

Please let me know if this doesn't work for you, but I'm going to close this issue for now as I'm fairly certain this should work for you.

**Comment by mtuckergd** [comment]
@salimane I'm also now seeing that the README wasn't updated to make this version split clear. Sorry about that. It was written up at some point and seems to have been lost. We'll get that updated to be clear in the future as well.

**Comment by salimane** [comment]
@mtuckergd yep the version ``0.0.2`` works. +1 for the readme update :)
Thanks
